<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<a href="<?php echo $this->getProductUrl() ?>"><strong><?php echo $this->getProductName() ?></strong></a>
<?php if ($_options = $this->getOptionList()): ?>
    <ul>
    <?php foreach ($_options as $option): ?>
        <?php
            $_randomId = str_replace('.', '_', 'truncated_' . microtime(true));
            $_truncatedRemainder = '';
            if (is_array($option['value'])) {
                $_truncatedValue = implode('<br />', $option['value']);
            } else {
                $_truncatedValue = Mage::helper('core/string')->truncate($option['value'], 100, '', $_truncatedRemainder);
                $_truncatedValue     = nl2br($this->htmlEscape($_truncatedValue));
                $_truncatedRemainder = nl2br($this->htmlEscape($_truncatedRemainder));
            }
            ?>
                <li<?php if ($_truncatedRemainder):?> id="<?php echo $_randomId?>" class="truncated"<?php endif; ?>><strong><?php echo $this->htmlEscape($option['label']) ?>:</strong><br />
                <?php if ($_truncatedRemainder):?>
                    <?php echo $_truncatedValue . '...'; ?>
                    <div class="truncated_value" id="<?php echo $_randomId?>_full_value"><strong><?php echo $option['label'] ?>:</strong> <?php echo $_truncatedValue . $_truncatedRemainder ; ?></div>
                    <script type="text/javascript">
                      Event.observe($('<?php echo $_randomId?>'), 'mouseover', function(){ $('<?php echo $_randomId?>_full_value').style.display="block"; });
                      Event.observe($('<?php echo $_randomId?>'), 'mouseout', function(){ $('<?php echo $_randomId?>_full_value').style.display="none"; });
                    </script>
                <?php else: ?>
                    <?php echo $_truncatedValue; ?>
                <?php endif; ?>
                </li>
    <?php endforeach; ?>
    </ul>
<?php endif; ?>
