<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php if($this->canDisplayGiftmessage()): ?>
<div id="<?php echo $this->getHtmlId() ?>" class="giftmessage-whole-order-container">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4><?php echo Mage::helper('sales')->__('Gift Message for Entire Order') ?></h4>
        </div>
        <fieldset>
            <form id="<?php echo $this->getFieldId('form') ?>" action="<?php echo $this->getSaveUrl() ?>">
            <input type="hidden" id="<?php echo $this->getFieldId('type') ?>" name="<?php echo $this->getFieldName('type') ?>" value="order"/>
            <table width="100%">
                <tr>
                    <td class="label"><label><?php echo Mage::helper('sales')->__('From Name') ?></label></td>
                    <td class="input-ele">
                        <input class="input-text" type="text" id="<?php echo $this->getFieldId('sender') ?>" name="<?php echo $this->getFieldName('sender') ?>" value="<?php echo $this->htmlEscape($this->getMessage()->getSender()) ?>"/>
                    </td>
                    <td></td>
                    <td class="label"><label><?php echo Mage::helper('sales')->__('To Name') ?></label></td>
                    <td class="input-ele">
                        <input class="input-text" type="text" id="<?php echo $this->getFieldId('recipient') ?>" name="<?php echo $this->getFieldName('recipient') ?>"  value="<?php echo $this->htmlEscape($this->getMessage()->getRecipient()) ?>"/>
                    </td>
                    <td></td>
                </tr>
                <tr>
                    <td class="label" colspan="6"><label><?php echo Mage::helper('sales')->__('Gift Message') ?></label></td>
                </tr>
                <tr>
                    <td colspan="5">
                        <textarea style="height:6em;padding-right:0px;padding-left:0px;" class="input-text" id="<?php echo $this->getFieldId('message') ?>" onchange="giftMessagesController.toogleRequired('<?php echo $this->getFieldId('message') ?>', ['<?php echo $this->getFieldId('sender') ?>','<?php echo $this->getFieldId('recipient') ?>']);" name="<?php echo $this->getFieldName('message') ?>"><?php echo $this->htmlEscape($this->getMessage()->getMessage()) ?></textarea>
                    </td>
                    <td></td>
                </tr>
                <tr>
                    <td alignt="right" colspan="6"><div class="right"><?php echo $this->getSaveButtonHtml() ?><div></td>
                </tr>
                </tbody>
            </table>
            </form>
        </fieldset>
    </div>
</div>
<?php endif ?>
