<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php if ($_item = $this->getItem()): ?>
<table cellpadding="0" cellspacing="0" width="100%" class="inline-table">
    <tr>
        <td><?php echo Mage::helper('sales')->__('Ordered') ?></td>
        <td><?php echo $_item->getQtyOrdered()*1 ?></td>
    </tr>
    <?php if ((float) $_item->getQtyInvoiced()): ?>
    <tr>
        <td><?php echo Mage::helper('sales')->__('Invoiced') ?></td>
        <td><?php echo $_item->getQtyInvoiced()*1 ?></td>
    </tr>
    <?php endif; ?>
    <?php if ((float) $_item->getQtyShipped()): ?>
    <tr>
        <td><?php echo Mage::helper('sales')->__('Shipped') ?></td>
        <td><?php echo $_item->getQtyShipped()*1 ?></td>
    </tr>
    <?php endif; ?>
    <?php if ((float) $_item->getQtyRefunded()): ?>
    <tr>
        <td><?php echo Mage::helper('sales')->__('Refunded') ?></td>
        <td><?php echo $_item->getQtyRefunded()*1 ?></td>
    </tr>
    <?php endif; ?>
    <?php if ((float) $_item->getQtyCanceled()): ?>
    <tr>
        <td><?php echo Mage::helper('sales')->__('Canceled') ?></td>
        <td><?php echo $_item->getQtyCanceled()*1 ?></td>
    </tr>
    <?php endif; ?>
</table>
<?php endif; ?>