<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="grid">
    <table cellspacing="0" class="data" id="invoice_items_grid_table">
        <col/>
        <col width="100"/>
        <col width="100"/>
        <col width="60"/>
        <col width="100"/>
        <col width="100"/>
        <col width="100"/>
        <col width="100"/>
        <thead>
            <tr class="headings">
                <th><?php echo Mage::helper('sales')->__('Product') ?></th>
                <th><?php echo Mage::helper('sales')->__('Price') ?></th>
                <th><?php echo Mage::helper('sales')->__('Qty') ?></th>
                <th><?php echo Mage::helper('sales')->__('Qty to Invoice') ?></th>
                <th><?php echo Mage::helper('sales')->__('Subtotal') ?></th>
                <th><?php echo Mage::helper('sales')->__('Tax Amount') ?></th>
                <th><?php echo Mage::helper('sales')->__('Discount Amount') ?></th>
                <th class="last"><?php echo Mage::helper('sales')->__('Row Total') ?></th>
            </tr>
        </thead>
        <tbody>
            <?php $_items = $this->getInvoice()->getAllItems() ?>
            <?php $_i=0;foreach ($_items as $_item):$_i++ ?>
                <?php $this->setPriceDataObject($_item) ?>
                <tr class="<?php echo $_i%2?'odd':'even' ?>">
                    <td>
                        <?php echo $_item->getName() ?>
                        <div class="nobr"><strong><?php echo $this->helper('sales')->__('SKU') ?>:</strong> <?php echo $_item->getSku() ?></div>
                        <?php echo $_item->getDescription() ?>
                    </td>
                    <td class="price"><?php echo $this->displayPriceAttribute('price') ?></td>
                    <td><?php echo $this->getQtyHtml($_item->getOrderItem()) ?></td>
                    <td class="a-center">
                    <?php if ($this->canEditQty()) : ?>
                        <input type="text" class="input-text qty-input" name="invoice[items][<?php echo $_item->getOrderItemId() ?>]" value="<?php echo $_item->getQty()*1 ?>"/>
                    <?php else : ?>
                        <?php echo $_item->getQty()*1 ?>
                    <?php endif; ?>
                    </td>
                    <td class="price"><?php echo $this->displayPriceAttribute('row_total') ?></td>
                    <td class="price"><?php echo $this->displayPriceAttribute('tax_amount') ?></td>
                    <td class="price"><?php echo $this->displayPriceAttribute('discount_amount') ?></td>
                    <td class="last price">
                        <?php echo $this->displayPrices(
                            $_item->getBaseRowTotal()+$_item->getBaseTaxAmount()-$_item->getBaseDiscountAmount(),
                            $_item->getRowTotal()+$_item->getTaxAmount()-$_item->getDiscountAmount()
                        ) ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
        <?php if ($this->canEditQty()): ?>
        <tfoot>
            <tr>
                <td colspan="2">&nbsp;</td>
                <td colspan="3" class="a-center">
                    <?php echo $this->getUpdateButtonHtml() ?>
                </td>
                <td colspan="3">&nbsp;</td>
            </tr>
        </tfoot>
        <?php endif; ?>
    </table>
</div>

<div class="clear"></div>
<?php echo $this->getChildHtml('totals_bar') ?>
<div class="clear"></div>

<div class="box-left entry-edit">
    <div class="entry-edit-head"><h4><?php echo $this->__('Invoice History') ?></h4></div>
    <fieldset>
        <div id="history_form" class="order-history-form">
            <span class="field-row">
                <label class="normal" for="history_comment"><?php echo Mage::helper('sales')->__('Invoice Comments') ?></label>
                <textarea id="invoice_comment_text" name="invoice[comment_text]" class="input-text" style="height: 10em; width: 98%;"></textarea>
            </span>
            <div class="clear"></div>
        </div>
    </fieldset>
</div>

<div class="box-right entry-edit" id="history_form">
    <div class="entry-edit-head"><h4><?php echo $this->__('Invoice Totals') ?></h4></div>
    <div class="order-totals">
        <?php echo $this->getChildHtml('totals') ?>
        <div class="divider"></div>

        <?php if ($this->canCapture()): ?>
        <p>
            <label for="invoice_do_capture" class="normal"><?php echo Mage::helper('sales')->__('Capture Amount') ?></label>
            <input type="checkbox" name="invoice[do_capture]" id="invoice_do_capture" value="1" checked/>
        </p>
        <?php endif; ?>
        <p>
            <label class="normal" for="notify_customer"><?php echo Mage::helper('sales')->__('Append Comments') ?></label>
            <input id="notify_customer" name="invoice[comment_customer_notify]" value="1" type="checkbox">
        </p>
        <p>
            <label class="normal" for="send_email"><?php echo Mage::helper('sales')->__('Email Copy of Invoice') ?></label>
            <input id="send_email" name="invoice[send_email]" value="1" type="checkbox">
        </p>
        <div class="a-right">
        <?php echo $this->getChildHtml('submit_button') ?>
        </div>
    </div>
</div>
<div class="clear"></div>

<table class="order-info-foot" cellpadding="10" cellspacing="0" width="100%">
    <tbody>
        <tr>
            <td class="section">
                <table id="comments_block" cellpadding="0" width="100%">
                    <tbody>
                        <tr>
                            <td style="padding-right: 30px;" width="50%"></td>
                            <td>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </td>

            <td class="document-totals section">
            </td>
        </tr>
    </tbody>
</table>

<script type="text/javascript">
var submitButtons = document.getElementsByClassName('submit-button');
var updateButtons = document.getElementsByClassName('update-button');
var fields = document.getElementsByClassName('qty-input');

updateButtons.each(function (elem) {elem.disabled=true;elem.addClassName('disabled');});

for(var i=0;i<fields.length;i++){
    fields[i].observe('change', checkButtonsRelation)
    fields[i].baseValue = fields[i].value;
}

function checkButtonsRelation() {
    var hasChanges = false;
    fields.each(function (elem) {
        if (elem.baseValue != elem.value) {
            hasChanges = true;
        }
    }.bind(this));
    if (hasChanges) {
        submitButtons.each(function (elem) {elem.disabled=true;elem.addClassName('disabled');});
        updateButtons.each(function (elem) {elem.disabled=false;elem.removeClassName('disabled');});
    }
    else {
        submitButtons.each(function (elem) {elem.disabled=false;elem.removeClassName('disabled');});
        updateButtons.each(function (elem) {elem.disabled=true;elem.addClassName('disabled');});
    }
}

var sendEmailCheckbox = $('send_email');
if (sendEmailCheckbox) {
    var notifyCustomerCheckbox = $('notify_customer');
    var invoiceCommentText = $('invoice_comment_text');
    Event.observe(sendEmailCheckbox, 'change', bindSendEmail);
    bindSendEmail();
}
function bindSendEmail()
{
    if (sendEmailCheckbox.checked == true) {
        notifyCustomerCheckbox.disabled = false;
        invoiceCommentText.disabled = false;
    }
    else {
        notifyCustomerCheckbox.disabled = true;
        invoiceCommentText.disabled = true;
    }
}
</script>