<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage_Bundle
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

?>
<?php $_product = $this->getProduct() ?>
<?php $_options = $this->getOptions() ?>

<?php echo $this->getPriceHtml($_product) ?>

<?php if($_product->isSaleable()): ?>

<script type="text/javascript">
var bundle = new Product.Bundle(<?php echo $this->getJsonConfig() ?>);
</script>

<?php /* @see bundle/options.phtml */ ?>

    <?php $_tierPrices = $this->getTierPrices() ?>
    <?php if(count($_tierPrices)>0): ?>
    <div class="product-pricing">
        <ul class="bare">
        <?php foreach($_tierPrices as $_price): ?>
            <li>
                <?php echo $this->__('Buy %s with %s%% discount each', $_price['price_qty'], $_price['price']*1) ?>
            </li>
        <?php endforeach ?>
        </ul>
    </div>
    <?php endif; ?>

    <p><small><?php echo $this->helper('catalog')->__('Availability: In stock.') ?></small></p>

    <?php $_finalPrice = Mage::helper('tax')->getPrice($_product, $_product->getFinalPrice()); ?>
    <?php $_finalPriceInclTax = Mage::helper('tax')->getPrice($_product, $_product->getFinalPrice(), true); ?>

    <?php if ($this->helper('tax')->displayBothPrices()): ?>
        <span class="price-excluding-tax">
            <span class="label"><?php echo $this->helper('tax')->__('Excl. Tax') ?>:</span>
            <span class="price" id="price-excluding-tax-<?php echo $_product->getId() ?>">
                <?php echo Mage::helper('core')->currency($_finalPrice) ?>
            </span>
        </span>
        <span class="price-including-tax">
            <span class="label"><?php echo $this->helper('tax')->__('Incl. Tax') ?>:</span>
            <span class="price" id="price-including-tax-<?php echo $_product->getId() ?>">
                <?php echo Mage::helper('core')->currency($_finalPriceInclTax) ?>
            </span>
        </span>
    <?php else: ?>
    <span class="regular-price" id="product-price-<?php echo $_product->getId() ?>">
        <?php echo Mage::helper('core')->currency($_finalPrice) ?>
    </span>
    <?php endif; ?>
<?php else: ?>
    <p><small><?php echo $this->helper('catalog')->__('Availability: Out of stock.') ?></small></p>
<?php endif; ?>
<script type="text/javascript">decorateTable('super-product-table')</script>