<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php if($this->getProduct()->getRatingSummary()->getReviewsCount()): ?>
    <div class="ratings">
        <div class="rating-box">
            <div class="rating" style="width:<?php echo $this->getProduct()->getRatingSummary()->getRatingSummary() ?>%;"></div>
        </div>
        ( <?php echo sprintf('%d', $this->getProduct()->getRatingSummary()->getReviewsCount()) ?> )
    </div>
<?php endif; ?>

<?php if( !$this->getProduct()->getRatingSummary()->getReviewsCount() && $this->getDisplayBlock() ): ?>
    <p><a href="<?php echo $this->getAddLink() ?>#review-form"><?php echo $this->__('Be the first to review this product') ?></a></p>
<?php endif; ?>