<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="grid">
    <table cellspacing="0" class="data">
        <col/>
        <col width="100"/>
        <col width="100"/>
        <thead>
            <tr class="headings">
                <th><?php echo $this->helper('sales')->__('Product') ?></th>
                <th><?php echo $this->helper('sales')->__('Qty') ?></th>
                <th class="last"><?php echo $this->helper('sales')->__('Qty to Ship') ?></th>
            </tr>
        </thead>
        <tbody>
            <?php $_items = $this->getShipment()->getAllItems() ?>
            <?php $_i=0;foreach ($_items as $_item):$_i++ ?>
                <tr class="<?php echo $_i%2?'odd':'even' ?>">
                    <td>
                        <?php echo $_item->getName() ?>
                        <div class="nobr"><strong><?php echo $this->helper('sales')->__('SKU') ?>:</strong> <?php echo $_item->getSku() ?></div>
                        <?php echo $_item->getDescription() ?>
                    </td>
                    <td><?php echo $this->getQtyHtml($_item->getOrderItem()) ?></td>
                    <td class="last">
                        <input type="text" class="input-text" name="shipment[items][<?php echo $_item->getOrderItemId() ?>]" value="<?php echo $_item->getQty()*1 ?>"/>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="box-left entry-edit">
    <div class="entry-edit-head"><h4><?php echo $this->__('Shipment Comments') ?></h4></div>
    <fieldset>
        <div id="history_form" class="order-history-form">
            <span class="field-row">
                <label class="normal" for="history_comment"><?php echo Mage::helper('sales')->__('Shipment Comments') ?></label>
                <textarea id="shipment_comment_text" name="shipment[comment_text]" class="input-text" style="height: 6em; width: 99%;"></textarea>
            </span>
            <div class="clear"></div>
        </div>
    </fieldset>
</div>

<div class="box-right entry-edit" id="history_form">
    <div class="order-totals">
        <p>
            <label class="normal" for="notify_customer"><?php echo Mage::helper('sales')->__('Append Comments') ?></label>
            <input id="notify_customer" name="shipment[comment_customer_notify]" value="1" type="checkbox">
        </p>
        <p>
            <label class="normal" for="send_email"><?php echo Mage::helper('sales')->__('Email Copy of Shipment') ?></label>
            <input id="send_email" name="shipment[send_email]" value="1" type="checkbox">
        </p>
        <div class="a-right">
        <?php echo $this->getChildHtml('submit_button') ?>
        </div>
    </div>
</div>
<div class="clear"></div>
<script type="text/javascript">
var sendEmailCheckbox = $('send_email');
if (sendEmailCheckbox) {
    var notifyCustomerCheckbox = $('notify_customer');
    var shipmentCommentText = $('shipment_comment_text');
    Event.observe(sendEmailCheckbox, 'change', bindSendEmail);
    bindSendEmail();
}
function bindSendEmail()
{
    if (sendEmailCheckbox.checked == true) {
        notifyCustomerCheckbox.disabled = false;
        shipmentCommentText.disabled = false;
    }
    else {
        notifyCustomerCheckbox.disabled = true;
        shipmentCommentText.disabled = true;
    }
}
</script>