<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<table cellspacing="0" class="data-table" id="checkout-review-table">
    <thead>
        <tr>
            <th><?php echo $this->__('Product Name') ?></th>
            <th class="a-right"><?php echo $this->__('Price') ?></th>
            <th class="a-center"><?php echo $this->__('Qty') ?></th>
            <th class="a-right"><?php echo $this->__('Subtotal') ?></th>
        </tr>
    </thead>
    <tfoot>
<?php $l=sizeof($this->getTotals()); $i=0; foreach($this->getTotals() as $total): $i++ ?>
        <tr>
            <td style="<?php echo $total->getStyle() ?>" class="a-right" colspan="3"><?php echo $total->getTitle() ?></td>
            <td style="<?php echo $total->getStyle() ?>" class="a-right"><?php echo $this->helper('checkout')->formatPrice($total->getValue()) ?></td>
        </tr>
<?php endforeach ?>
    </tfoot>
    <tbody>
<?php $l=sizeof($this->getItems()); $i=0; foreach($this->getItems() as $item): $i++ ?>
        <tr>
            <td>
                <?php echo $this->htmlEscape($item->getName()) ?>
                <?php echo $this->helper('checkout')->getQuoteItemProductDescription($item) ?>
            </td>
            <td class="a-right"><?php echo $this->helper('checkout')->formatPrice($item->getCalculationPrice()) ?></td>
            <td class="a-center"><?php echo $item->getQty()*1 ?></td>
            <td class="a-right"><?php echo $this->helper('checkout')->formatPrice($item->getRowTotal()) ?></td>
        </tr>
<?php endforeach ?>
    </tbody>
</table>
<script type="text/javascript">decorateTable('checkout-review-table')</script>
