<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php if($this->canDisplayContainer()): ?>
<div id="<?php echo $this->getHtmlId() ?>" class="item-container f-left">
<?php endif; ?>
<?php if($this->canDisplayGiftmessage()): ?>
<div class="item-text">
    <div><?php echo $this->htmlEscape($this->getEntity()->getName()) ?></div>
    <div class="nobr"><strong><?php echo $this->helper('sales')->__('SKU') ?>:</strong> <?php echo $this->getEntity()->getSku() ?></div>
    <?php echo $this->getEntity()->getDescription() ?>
    <div>
        <a class="action-link" href="#" onclick="return giftMessagesController.toogleGiftMessage('<?php echo $this->getHtmlId() ?>')">
        <span class="default-text">
            <?php if(!$this->getMessage()->getId()): ?>
                <?php echo $this->helper('sales')->__('Add Gift Messsage') ?>
            <?php else: ?>
                <?php echo $this->helper('sales')->__('Edit Gift Messsage') ?>
            <?php endif ?>
        </span>
        <span class="close-text" style="display:none">
            <?php echo $this->helper('sales')->__('Save and Close Message') ?>
        </span>
        </a>
    </div>
</div>
<div class="gift-form" style="display:none;" id="<?php echo $this->getFieldId('edit') ?>">
<form id="<?php echo $this->getFieldId('form') ?>" action="<?php echo $this->getSaveUrl() ?>">
    <div class="entry-edit">
        <fieldset>
            <input type="hidden" id="<?php echo $this->getFieldId('type') ?>" name="<?php echo $this->getFieldName('type') ?>" value="order_item"/>
            <span class="field-row f-left">
                <label><?php echo $this->helper('sales')->__('From Name') ?></label><br />
                <input class="input-text" type="text" id="<?php echo $this->getFieldId('sender') ?>" name="<?php echo $this->getFieldName('sender') ?>" value="<?php echo $this->htmlEscape($this->getMessage()->getSender()) ?>"/>
            </span>
            <span class="field-row f-left last">
                <label><?php echo $this->helper('sales')->__('To Name') ?></label><br />
                <input class="input-text" type="text" id="<?php echo $this->getFieldId('recipient') ?>" name="<?php echo $this->getFieldName('recipient') ?>"  value="<?php echo $this->htmlEscape($this->getMessage()->getRecipient()) ?>"/>
            </span>
            <div class="clear"></div>
            <span class="field-row">
                <label><?php echo $this->helper('sales')->__('Gift Message') ?></label><br />
                <textarea class="input-text" id="<?php echo $this->getFieldId('message') ?>" onchange="giftMessagesController.toogleRequired('<?php echo $this->getFieldId('message') ?>', ['<?php echo $this->getFieldId('sender') ?>','<?php echo $this->getFieldId('recipient') ?>']);" name="<?php echo $this->getFieldName('message') ?>"><?php echo $this->htmlEscape($this->getMessage()->getMessage()) ?></textarea>
            </span>
        </fieldset>
    </div>
</form>
</div>
<?php else: ?>
<div class="item-text">
    <?php echo $this->htmlEscape($this->getEntity()->getName()) ?>
    <div class="nobr"><strong><?php echo $this->helper('sales')->__('SKU') ?>:</strong> <?php echo $this->getEntity()->getSku() ?></div>
        <?php echo $this->getEntity()->getDescription() ?>
    </div>
<?php endif; ?>
<?php if($this->canDisplayContainer()): ?>
</div>
<?php endif ?>