<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php /*{
    "label":"Root page layout",
    "type":"core/template",
    "children":{
        "header":{ "label":"Header", "type":"adminhtml/page_header" },
        "menu":{ "label":"Top navigation", "type":"adminhtml/page_menu" },
        "breadcrumbs":{ "label":"Breadcrumbs", "type":"adminhtml/widget_breadcrumbs" },
        "content":{ "label":"Content block", "type":"core/template" },
        "left":{ "label":"Left navigation", "type":"core/template" },
        "footer":{ "label":"Footer", "type":"adminhtml/page_footer" }
    },
    "vars":{}
}*/ ?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html lang="en">
<head>
    <?php echo $this->getChildHtml('head') ?>
</head>
<body id="html-body" class="html-body-popup">
<![if !IE]><table cellspacing="0" width="100%"><tr><td><![endif]>
<div>
        <div class="middle-popup">
            <div class="middle" id="anchor-content">
                <div id="page:main-container">
                <?php if($this->getChildHtml('left')): ?>
                    <div class="<?php echo $this->getContainerCssClass() ?>" id="page:container">
                        <table cellspacing="0" width="100%">
                            <tr>
                                <td class="side-col" id="page:left">
                                    <?php echo $this->getChildHtml('left') ?>
                                </td>
                                <td class="main-col" id="content">
                                    <div id="messages"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
                                    <?php echo $this->getChildHtml('content') ?>
                                </td>
                            </tr>
                        </table>
                    </div>
                <?php else: ?>
                    <div id="messages"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
                    <?php echo $this->getChildHtml('content') ?>
                <?php endif; ?>
                </div>
            </div>
        </div>

        <div class="footer">
            <?php echo $this->getChildHtml('footer') ?>
        </div>
       </div>
<![if !IE]></td></tr></table><![endif]>
        <?php echo $this->getChildHtml('js') ?>

<?php echo $this->getChildHtml('profiler') ?>
<div id="loading-mask" style="display:none">
    <p class="loader" id="loading_mask_loader"><img src="<?php echo $this->getSkinUrl('images/ajax-loader-tr.gif') ?>" alt="<?php echo Mage::helper('adminhtml')->__('Loading...') ?>"/><br/><?php echo Mage::helper('adminhtml')->__('Please wait...') ?></p>
</div>

<?php echo $this->getChildHtml('before_body_end') ?>
</body>
</html>