<?php if($this->getIsShipping()):
    $_fieldsContainerId = 'order:shipping_address_fields';
    ?>
    <script type="text/javascript">
    order.shippingAddressContainer = '<?php echo $_fieldsContainerId ?>';
    order.setAddresses(<?php echo $this->getAddressCollectionJson() ?>);
    </script>
    <?php 
else:
    $_fieldsContainerId = 'order:billing_address_fields';
    ?>
    <script type="text/javascript">
    order.billingAddressContainer = '<?php echo $_fieldsContainerId ?>';
    </script>
    <?php 
endif; ?>
<div class="entry-edit">

    <div class="entry-edit-head">
        <h4 class="icon-head fieldset-legend <?php echo $this->getHeaderCssClass() ?>"><?php echo $this->getHeaderText() ?></h4>
     </div>

    <fieldset class="np">
    <div class="order-choose-address">
        <?php echo Mage::helper('sales')->__('Select from existing customer addresses:') ?><br/>
        <?php $_id = $this->getForm()->getHtmlIdPrefix() . 'customer_address_id' ?>
        <select id="<?php echo $_id ?>" style="width:97.5%;" onchange="order.selectAddress(this.value, '<?php echo $_fieldsContainerId ?>')">
            <option value=""><?php echo Mage::helper('sales')->__('Add New Address') ?></option>
            <?php foreach ($this->getAddressCollection() as $_address): ?>
            <?php //if($this->getAddressAsString($_address)!=$this->getAddressAsString($this->getAddress())): ?>
            <option value="<?php echo $_address->getId() ?>"<?php if ($_address->getId()==$this->getAddressId()): ?> selected="selected"<?php endif; ?>>
                <?php echo $this->getAddressAsString($_address) ?>
            </option>
            <?php //endif; ?>
            <?php endforeach; ?>

        </select>
        <br/>
        <?php if($this->getIsShipping()): ?>
            <input type="checkbox" id="order:shipping_same_as_billing" name="shipping_same_as_billing" onchange="order.setShippingAsBilling(this.checked)" <?php if($this->getIsAsBilling()): ?>checked<?php endif; ?>/>
            <label for="order:shipping_same_as_billing" class="no-float"><?php echo Mage::helper('sales')->__('Same As Billing Address') ?></label>
        <?php else: ?>
            &nbsp;
        <?php endif; ?>
    </div>

    <div class="content order-address" id="<?php echo $_fieldsContainerId ?>">
        <?php echo $this->getForm()->toHtml() ?>
    </div>
    <script type="text/javascript">
        order.bindAddressFields('<?php echo $_fieldsContainerId ?>')
        <?php if($this->getIsShipping() && $this->getIsAsBilling()): ?>
        order.disableShippingAddress(true);
        <?php endif; ?>
    </script>
    </fieldset>
</div>