<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */


/**
 * Super product options
 *
 * @see Mage_Catalog_Block_Product_View_Super_Config
 */
?>
<?php $_product = $this->getProduct() ?>
<?php if($_product->isSaleable()): ?>

    <?php $_tierPrices = $this->getTierPrices() ?>
    <?php if(count($_tierPrices)>0): ?>
    <div class="product-pricing">
        <ul class="bare">
        <?php foreach($_tierPrices as $_price): ?>
            <?php if ($this->helper('tax')->displayBothPrices() && $_price['formated_price'] != $_price['formated_price_incl_tax']): ?>
                <li><?php echo $this->__('Buy %s for %s (%s incl. tax) each', '<strong>'.$_price['price_qty'].'</strong>', $_price['formated_price'], '<strong>'.$_price['formated_price_incl_tax'].'</strong>') ?>
            <?php else: ?>
                <li><?php echo $this->__('Buy %s for %s each', '<strong>'.$_price['price_qty'].'</strong>',  '<strong>'.$_price['formated_price'].'</strong>') ?>
            <?php endif; ?>
            <?php if(($_product->getPrice() == $_product->getFinalPrice() && $_product->getPrice() > $_price['price'])
            || ($_product->getPrice() != $_product->getFinalPrice() &&  $_product->getFinalPrice() > $_price['price'])): ?>
                <?php echo $this->__('and') ?>&nbsp;<strong class="benefit"><?php echo $this->__('save %s%%', $_price['savePercent']) ?>
            <?php endif ?></strong>
            </li>
        <?php endforeach ?>
        </ul>
    </div>
    <?php endif; ?>

    <p><small><?php echo $this->__('Availability: In stock.') ?></small></p>
<?php else: ?>
    <p><small><?php echo $this->__('Availability: Out of stock.') ?></small></p>
<?php endif; ?>

<?php echo $this->getPriceHtml($_product) ?>

<script type="text/javascript">
var spConfig = new Product.Config(<?php echo $this->getJsonConfig() ?>);
</script>