<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Grouped product data template
 *
 * @see Mage_Catalog_Block_Product_View_Media
 */
?>
<?php $_product = $this->getProduct() ?>
<?php $_associatedProducts = $this->getAssociatedProducts() ?>
<table cellspacing="0" class="data-table" id="super-product-table">
    <thead>
        <tr>
            <th><?php echo $this->__('Product Name') ?></th>
            <th class="a-right"><?php echo $this->__('Price') ?></th>
            <?php if ($_product->isSaleable()): ?>
            <th class="a-center"><?php echo $this->__('Qty') ?></th>
            <?php endif; ?>
        </tr>
    </thead>
    <tbody>
    <?php if (count($_associatedProducts)): ?>
    <?php foreach ($_associatedProducts as $_item): ?>
        <tr>
            <td><?php echo $this->htmlEscape($_item->getName()) ?></td>
            <td class="a-right">
                <?php $_price = $_item->getPrice() ?>
                <?php $_finalPrice = $_item->getFinalPrice() ?>
                <?php if ($_finalPrice == $_price): ?>
                    <span class="nobr"><?php echo Mage::helper('core')->currency($_price) ?></span><br />
                <?php else: ?>
                    <span class="nobr old-price"><?php echo $this->__('Price') ?>&nbsp;<?php echo Mage::helper('core')->currency($_price) ?></span><br />
                    <span class="nobr special-price" style="font-size:12px;"><?php echo $this->__('Special Price') ?>&nbsp;<?php echo Mage::helper('core')->currency($_finalPrice) ?></span>
                <?php endif; ?>
                <?php if($_item->getTierPriceCount()): ?>
                    <?php foreach ($_item->getFormatedTierPrice() as $_tierPrice): ?>
                        <?php if($_tierPrice['price'] <= $_finalPrice): ?>
                            <span class="nobr"><?php echo $this->__('Buy %s for %s', $_tierPrice['price_qty']*1, $_tierPrice['formated_price']) ?></span>
                        <?php endif; ?>
                    <?php endforeach; ?>
                <?php endif; ?>
            </td>
            <?php if ($_product->isSaleable()): ?>
            <td class="a-center">
            <?php if ($_item->isSaleable()) : ?>
                <input name="super_group[<?php echo $_item->getId() ?>]" value="<?php echo $_item->getQty()*1 ?>" type="text" class="input-text qty"/>
            <?php else: ?>
                <?php echo $this->__('Out of stock.') ?>
            <?php endif; ?>
            </td>
            <?php endif; ?>
        </tr>
    <?php endforeach; ?>
    <?php else: ?>
       <tr>
           <td colspan="<?php if ($_product->isSaleable()): ?>4<?php else : ?>3<?php endif; ?>"><?php echo $this->__('No options of this product are available.') ?></td>
       </tr>
    <?php endif; ?>
    </tbody>
</table>

<script type="text/javascript">decorateTable('super-product-table')</script>

<?php if($_product->isSaleable() && count($_associatedProducts)): ?>
    <p><small><?php echo $this->__('Availability: In stock.') ?></small></p>
    <?php if($_product->isSaleable()): ?>
        <button class="form-button" onclick="productAddToCartForm.submit()"><span><?php echo $this->__('Add to Cart') ?></span></button>
        <?php if( $this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
            <strong><?php echo $this->__('OR') ?></strong>
        <?php endif; ?>
        &nbsp;&nbsp;
    <?php endif; ?>
<?php else: ?>
    <p><small><?php echo $this->__('Availability: Out of stock.') ?></small></p>
<?php endif; ?>

<?php if ($this->helper('wishlist')->isAllow()) : ?>
    <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"><?php echo $this->__('Add to Wishlist') ?></a>
<?php endif; ?>

<?php if($_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
    <span class="pipe">|</span>
    <a href="<?php echo $_compareUrl ?>"><?php echo $this->__('Add to Compare') ?></a>
<?php endif; ?>
