<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php echo $this->getBlockBefore()->getChildHtml('', true, true); ?>

<?php
$_children = $this->getSortedChildBlocks();
foreach ($_children as $_key => $_child) {
    if (!$_child->hasOptions()) {
        unset($_children[$_key]);
    }
}
$_children = Mage::helper('core')->decorateArray($_children);
?>
<?php if ($_children):?>
<div class="product-attributes">
  <fieldset class="product-options">
    <?php foreach ($_children as $_child):?>
        <?php echo $_child->toHtml()?>
    <?php endforeach;?>
  </fieldset>
</div>
<?php else: ?>
<!-- container is empty -->
<?php endif;?>

<?php echo $this->getBlockAfter()->getChildHtml('', true, true); ?>