<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<div class="page-head">
    <h3><?php echo $this->__('Your order has been received') ?></h3>
</div>
<p><strong><?php echo $this->__('Thank you for your purchase!') ?></strong></p>
<p>
        <?php echo $this->__('Your order # is: %s', Mage::getSingleton('checkout/session')->getLastRealOrderId()) ?>.<br/>
        <?php echo $this->__('You will receive an order confirmation email with details of your order and a link to track its progress.') ?>
</p>
<div class="button-set">
        <button  class="form-button" onclick="window.location='<?php echo $this->getUrl() ?>'"><span><?php echo $this->__('Continue Shopping') ?></span></button>
</div>
