<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="discount-codes box">
    <form action="<?php echo $this->getUrl('checkout/cart/couponPost') ?>" method="post">
    <fieldset>
    <h4><?php echo $this->__('Discount Codes') ?></h4>
    <p><?php echo $this->__('Enter your coupon code if you have one.') ?></p>
    <input class="input-text left" id="coupon_code" name="coupon_code" value="<?php echo $this->htmlEscape($this->getCouponCode()) ?>" name="do"/> &nbsp;<button class="form-button-alt" type="button" onclick="return this.form.submit();" name="do" value="<?php echo $this->__('Apply Coupon') ?>"><span><?php echo $this->__('Apply Coupon') ?></span></button>
    <div class="clear"></div>
    </fieldset>
</form>
</div>
