<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * Shoping cart sidebar
 *
 * @see Mage_Checkout_Block_Cart_Sidebar
 */
?>
<?php if($this->getCanDisplayCart()): ?>
<div class="box base-mini mini-cart">
    <div class="head">
        <?php $_cartQty = $this->getSummaryCount() ?>
        <h4><?php echo $this->__('My Cart') ?></h4>
        <?php if ($_cartQty>0): ?>
            <?php if ($_cartQty==1): ?>
            <?php echo $this->__('There is <a href="%s"><strong>1 item</strong></a> in your cart.', $this->getUrl('checkout/cart')) ?>
            <?php else: ?>
            <?php echo $this->__('There are <a href="%s"><strong>%s items</strong></a> in your cart.', $this->getUrl('checkout/cart'), $_cartQty) ?>
            <?php endif ?>
           <p class="subtotal"><?php echo $this->__('Cart Subtotal:') ?> <strong><?php echo Mage::helper('core')->formatPrice($this->getSubtotal()) ?></strong>
        <?php endif ?>
    </div>
    <?php $_items = $this->getRecentItems() ?>
    <?php if(count($_items)): ?>
        <div class="actions">
            <button class="form-button" type="button" onclick="setLocation('<?php echo $this->getUrl('checkout/onepage') ?>')"><span><?php echo $this->__('Checkout') ?></span></button>
        </div>
    <?php endif ?>
    <?php if(count($_items)): ?>
    <h5>Recently added item(s)</h5>
    <ol id="cart-sidebar">
    <?php foreach($_items as $_item): ?>
        <li>
            <div class="product-images">
                <a href="<?php echo $_item->getProductUrl() ?>"><img src="<?php echo $this->helper('catalog/image')->init($_item->getThumbnailObject(), 'thumbnail')->resize(50, 50)->setWatermarkSize('30x10'); ?>" alt="<?php echo $_item->getProductName() ?>" width="50" height="50" /></a>
            </div>
            <div class="product-details">
                <a href="<?php echo $this->getRemoveItemUrl($_item) ?>" onclick="return confirm('<?php echo $this->__('Are you sure you would like to remove this item from the shopping cart?') ?>');" class="widget-btn"><img src="<?php echo $this->getSkinUrl('images/list_remove_btn.gif') ?>" alt="<?php echo $this->__('Remove Product') ?>"/></a>
                <a href="<?php echo $_item->getProductUrl() ?>"><?php echo $_item->getProductName() ?></a>
                <?php echo $_item->getProductDescription() ?>
                <br/><strong><?php echo 1*$_item->getQty() ?></strong> x <?php echo Mage::helper('core')->currency($_item->getPrice()) ?>
            </div>
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('cart-sidebar')</script>
    <?php else: ?>
    <div class="content"><p><?php echo $this->__('You have no items in your cart.') ?></p></div>
    <?php endif ?>
</div>
<!-- [ends] .cart-sidebar // -->
<?php endif ?>
