<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage_Bundle
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php $_product = $this->getProduct() ?>
<?php list($_minimalPrice, $_maximalPrice) = $_product->getPriceModel()->getPrices($_product) ?>
<?php $_id = $_product->getId() ?>

<?php $_minimalPriceTax = Mage::helper('tax')->getPrice($_product, $_minimalPrice); ?>
<?php $_minimalPriceInclTax = Mage::helper('tax')->getPrice($_product, $_minimalPrice, true); ?>

<div class="price-box">
        <?php if ($_product->getPriceView()): ?>
            <span class="minimal-price"><span class="label"><?php echo $this->__('As low as') ?>:</span>
            <?php if ($this->helper('tax')->displayBothPrices() && ($_minimalPriceTax != $_minimalPriceInclTax)): ?>
                <?php echo Mage::helper('core')->currency($_minimalPriceTax) ?></span>
                <span class="price-including-tax">(<?php echo Mage::helper('core')->currency($_minimalPriceInclTax) ?> <span class="label"><?php echo Mage::helper('tax')->__('Incl. Tax') ?></span>)</span>
            <?php else: ?>
            <span class="regular-price"><?php echo Mage::helper('core')->currency($_minimalPriceTax) ?></span></span>
            <?php endif; ?>
        <?php else: ?>
            <?php if ($_minimalPrice <> $_maximalPrice): ?>
                <span class="price-from"><span class="label"><?php echo $this->__('From:') ?></span>
                <?php if ($this->helper('tax')->displayBothPrices() && ($_minimalPriceTax != $_minimalPriceInclTax)): ?>
                    <?php echo Mage::helper('core')->currency($_minimalPriceTax) ?></span>
                    <span class="price-including-tax">(<?php echo Mage::helper('core')->currency($_minimalPriceInclTax) ?> <span class="label"><?php echo Mage::helper('tax')->__('Incl. Tax') ?></span>)</span>
                <?php else: ?>
                    <?php echo Mage::helper('core')->currency($_minimalPriceTax) ?>
                </span>
                <?php endif; ?>

                <?php $_maximalPriceTax = Mage::helper('tax')->getPrice($_product, $_maximalPrice); ?>
                <?php $_maximalPriceInclTax = Mage::helper('tax')->getPrice($_product, $_maximalPrice, true); ?>

                <span class="price-to"><span class="label"><?php echo $this->__('To:') ?></span>
                <?php if ($this->helper('tax')->displayBothPrices() && ($_maximalPriceTax != $_maximalPriceInclTax)): ?>
                    <?php echo Mage::helper('core')->currency($_maximalPriceTax) ?></span>
                    <span class="price-including-tax">(<?php echo Mage::helper('core')->currency($_maximalPriceInclTax) ?> <span class="label"><?php echo Mage::helper('tax')->__('Incl. Tax') ?></span>)</span>
                <?php else: ?>
                    <?php echo Mage::helper('core')->currency($_maximalPriceTax) ?>
                </span>
                <?php endif; ?>
            <?php else: ?>
                <?php if ($this->helper('tax')->displayBothPrices() && ($_minimalPriceTax != $_minimalPriceInclTax)): ?>
                    <span class="regular-price"><?php echo Mage::helper('core')->currency($_minimalPriceTax) ?></span><br />
                    <span class="price-including-tax">(<?php echo Mage::helper('core')->currency($_minimalPriceInclTax) ?> <span class="label"><?php echo Mage::helper('tax')->__('Incl. Tax') ?></span>)</span>
                <?php else: ?>
                    <span class="regular-price"><?php echo Mage::helper('core')->currency($_minimalPriceTax) ?></span>
                <?php endif; ?>
            <?php endif; ?>
        <?php endif; ?>
</div>