<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="home-spot">
    <p class="home-callout"><img src="<?php echo $this->getSkinUrl('images/home_main_callout.jpg') ?>" alt=""/></p>
    <p class="home-callout"><img src="<?php echo $this->getSkinUrl('images/free_shipping_callout.jpg') ?>" alt=""/></p>
    <div class="box best-selling">
        <h3><?php echo $this->__('Best Selling Products') ?></h3>
        <table cellspacing="0">
            <tr class="odd">
                <td><a href="#"><img src="<?php echo $this->getSkinUrl('images/best_selling_img04.jpg') ?>" width="95" alt="" class="product-img"/></a>
                  <div class="product-description">
                    <p><a href="#" class="product-name"><?php echo $this->__('Zynicon Cinema Display 19-inch LCD monitor') ?></a></p>
                    <p><a href="#"><?php echo $this->__('See all %s', "<a href=\"#\">".$this->__("Computers")) ?></a></p>
                   </div></td>
                <td><a href="#"><img src="<?php echo $this->getSkinUrl('images/best_selling_img06.jpg') ?>" width="95" alt="" class="product-img"/></a>
                  <div class="product-description">
                    <p><a href="#" class="product-name"><?php echo $this->__('Sandra Mashiso Red Business shoes') ?></a></p>
                    <p><a href="#"><?php echo $this->__('See all %s', "<a href=\"#\">".$this->__("Shoes")) ?></a></p>
                   </div></td>
            </tr>
            <tr class="even">
                <td><a href="#"><img src="<?php echo $this->getSkinUrl('images/best_selling_img03.jpg') ?>" width="95" alt="" class="product-img"/></a>
                  <div class="product-description">
                    <p><a href="#" class="product-name"><?php echo $this->__('Panasoic HDC-SD1 High Definition Camcorder') ?></a></p>
                    <p><a href="#"><?php echo $this->__('See all %s', "<a href=\"#\">".$this->__("Shoes")) ?></a></p>
                   </div></td>
                <td><a href="#"><img src="<?php echo $this->getSkinUrl('images/best_selling_img01.jpg') ?>" width="95" alt="" class="product-img"/></a>
                  <div class="product-description">
                    <p><a href="#" class="product-name"><?php echo $this->__('Zynicon Clear Blue 24-inch LCD monitor') ?></a></p>
                    <p><a href="#"><?php echo $this->__('See all %s', "<a href=\"#\">".$this->__("Women's Shoes")) ?></a></p>
                  </div></td>
            </tr>
            <tr class="odd">
                <td><a href="#"><img src="<?php echo $this->getSkinUrl('images/best_selling_img05.jpg') ?>" width="95" alt="" class="product-img"/></a>
                  <div class="product-description">
                    <p><a href="#" class="product-name"><?php echo $this->__('Kamper state-of-art Extra Comfort runners') ?></a></p>
                    <p><a href="#"><?php echo $this->__('See all %s', "<a href=\"#\">".$this->__("Shoes")) ?></a></p>
                   </div></td>
                <td><a href="#"><img src="<?php echo $this->getSkinUrl('images/best_selling_img02.jpg') ?>" width="95" alt="" class="product-img"/></a>
                  <div class="product-description">
                    <p><a href="#" class="product-name"><?php echo $this->__("Clean boot cut women's business pant") ?></a></p>
                    <p><a href="#"><?php echo $this->__('See all %s', "<a href=\"#\">".$this->__("Women's Shoes")) ?></a></p>
                   </div></td>
             </tr>
        </table>
       </div>
</div>
