<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php $_order = $this->getOrder() ?>
<!--<div class="page-head button-level">
    <h2><?php echo $this->__('Refunds') ?></h2>
    <button class="form-button" onclick="window.print();"><span><?php echo $this->__('Print All Refunds') ?></span></button>
</div>-->
<h3><?php echo $this->__('Order #%s', $_order->getRealOrderId()) ?></h3>
<?php $_creditmemo = $this->getCreditmemo() ?>
<?php if($_creditmemo): ?>
    <?php $_creditmemos = array($_creditmemo); ?>
<?php else: ?>
    <?php $_creditmemos = $_order->getCreditmemosCollection() ?>
<?php endif; ?>
<?php foreach ($_creditmemos as $_creditmemo): ?>
    <div class="divider"></div>
    <div class="head">
        <h3><?php echo $this->__('Refund #%s', $_creditmemo->getIncrementId()) ?></h3>
        <!--<a href="#"><?php echo $this->__('Print Invoice') ?></a>-->
    </div>
    <div class="col2-set">
        <div class="col-1">
            <h4><?php echo $this->__('Shipping Address') ?></h4>
            <?php $_shipping = $_creditmemo->getShippingAddress() ?>
            <address><?php echo $_shipping->format('html') ?></address>
        </div>
        <div class="col-2">
            <h4><?php echo $this->__('Billing Address') ?></h4>
            <?php $_billing = $_creditmemo->getbillingAddress() ?>
            <address><?php echo $_order->getBillingAddress()->format('html') ?></address>
        </div>
    </div>
    <br/>
    <div class="col2-set">
        <div class="col-1">
            <h4><?php echo $this->__('Shipping Method') ?></h4>
             <?php echo $_order->getShippingDescription() ?>
        </div>
        <div class="col-2">
            <h4><?php echo $this->__('Payment Method') ?></h4>
            <?php echo $this->getPaymentInfoHtml() ?>
        </div>
    </div>
    <br/>
    <h4><?php echo $this->__('Items Ordered') ?></h4>
    <table cellspacing="0" class="data-table" id="my-orders-table">
    <thead>
        <tr>
            <th><?php echo $this->__('Product Name') ?></th>
            <th width="10%"><?php echo $this->__('SKU') ?></th>
            <th width="10%"><?php echo $this->__('Price') ?></th>
            <th class="a-center" width="5%"><?php echo $this->__('Qty') ?></th>
            <th><?php echo $this->__('Subtotal') ?></th>
            <th class="wrap" width="7%"><?php echo $this->__('Tax Amount') ?></th>
            <th class="wrap" width="7%"><?php echo $this->__('Discount Amount') ?></th>
            <th class="wrap"><?php echo $this->__('Row Total') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php $_items = $_creditmemo->getAllItems(); ?>
        <?php $_count = count($_items); ?>
        <?php $_index = 0; ?>
        <?php foreach ($_items as $_item): ?>
            <tr <?php echo ($_index++ > $_count ? ' class="last"' : '') ?> id="order-item-row-<?php echo $_item->getId() ?>">
                <td>
                    <?php echo $this->htmlEscape($_item->getName()) ?>
                    <?php echo $_item->getDescription() ?>
                </td>
                <td><?php echo $_item->getSku() ?></td>
                <td class="a-right nowrap"><?php echo $_order->formatPrice($_item->getPrice()) ?> </td>
                <td><?php echo $_item->getQty()*1 ?></td>
                <td class="a-right"><?php echo $_order->formatPrice($_item->getRowTotal()) ?></td>
                <td class="a-right"><?php echo $_order->formatPrice($_item->getTaxAmount()) ?></td>
                <td class="a-right"><?php echo $_order->formatPrice(-$_item->getDiscountAmount()) ?></td>
                <td class="last a-right nowrap">
                    <?php echo $_order->formatPrice($_item->getRowTotal()-$_item->getDiscountAmount()+$_item->getTaxAmount()) ?>
                </td>
            </tr>
        <?php endforeach; ?>

    </tbody>
    <tfoot>
            <?php if ((float) $_creditmemo->getSubtotal()): ?>
        <tr>
            <td colspan="7" class="a-right"><?php echo $this->__('Subtotal') ?></td>
            <td class="last a-right"><?php echo $_order->formatPrice($_creditmemo->getSubtotal()) ?></td>
        </tr>
        <?php endif; ?>
        <?php if ((float) $_creditmemo->getTaxAmount()): ?>
        <tr>
            <td colspan="7" class="a-right"><?php echo $this->__('Tax') ?></td>
            <td class="last a-right"><?php echo $_order->formatPrice($_creditmemo->getTaxAmount()) ?></td>
        </tr>
        <?php endif; ?>

        <?php if ((float) $_creditmemo->getShippingAmount() || $_creditmemo->getShippingDescription()): ?>
        <tr>
            <td colspan="7" class="a-right"><?php echo $this->__('Shipping') ?></td>
            <td class="last a-right"><?php echo $_order->formatPrice($_creditmemo->getShippingAmount()) ?></td>
        </tr>
        <?php endif; ?>
        <?php if ((float) $_creditmemo->getDiscountAmount()): ?>
        <tr>
            <td colspan="7" class="a-right"><?php echo $this->__('Discount') ?></td>
            <td class="last a-right"><?php echo $_order->formatPrice(-$_creditmemo->getDiscountAmount()) ?></td>
        </tr>
        <?php endif; ?>

        <?php if ((float) $_creditmemo->getGiftcertAmount()): ?>
        <tr>
            <td colspan="7" class="a-right"><?php echo $this->__('Gift Certificate') ?></td>
            <td class="last a-right"><?php echo $_order->formatPrice($_creditmemo->getGiftcertAmount()) ?></td>
        </tr>
        <?php endif; ?>

        <?php if ((float) $_creditmemo->getAdjustmentPositive()): ?>
        <tr>
            <td colspan="7" class="a-right"><?php echo $this->__('Adjustment Refund') ?></td>
            <td class="last a-right"><?php echo $_order->formatPrice($_creditmemo->getAdjustmentPositive()) ?></td>
        </tr>
        <?php endif; ?>

        <?php if ((float) $_creditmemo->getAdjustmentNegative()): ?>
        <tr>
            <td colspan="7" class="a-right"><?php echo $this->__('Adjustment Fee') ?></td>
            <td class="last a-right"><?php echo $_order->formatPrice($_creditmemo->getAdjustmentNegative()) ?></td>
        </tr>
        <?php endif; ?>
         <tr>
            <td colspan="7" class="a-right">
                <strong><?php echo $this->__('Grand Total') ?></strong>
            </td>
            <td class="last a-right">
                <strong><?php echo $_order->formatPrice($_creditmemo->getGrandTotal()) ?></strong>
            </td>
        </tr>
        <?php if ($this->getCanDisplayTotalPaid()): ?>
        <tr>
            <td colspan="7" class="a-right">
                <strong><?php echo $this->__('Total Paid') ?></strong>
            </td>
            <td class="last a-right">
                <strong><?php echo $_order->formatPrice($_creditmemo->getTotalPaid()) ?></strong>
            </td>
        </tr>
        <?php endif; ?>
        <?php if ($this->getCanDisplayTotalRefunded()): ?>
        <tr>
            <td colspan="7" class="a-right">
                <strong><?php echo $this->__('Total Refunded') ?></strong>
            </td>
            <td class="last a-right">
                <strong><?php echo $_order->formatPrice($_creditmemo->getTotalRefunded()) ?></strong>
            </td>
        </tr>
        <?php endif; ?>
        <?php if ($this->getCanDisplayTotalDue()): ?>
        <tr>
            <td colspan="7" class="a-right">
                <strong><?php echo $this->__('Total Due') ?></strong>
            </td>
            <td class="last a-right">
                <strong><?php echo $_order->formatPrice($_creditmemo->getTotalDue()) ?></strong>
            </td>
        </tr>
        <?php endif; ?>
    </tfoot>
</table>
    <br/>
<?php endforeach; ?>
<script type="text/javascript">window.print();</script>