<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<input type="hidden" id="<?php echo $this->getId() ?>_raw_options" name="_options_json">
<table cellspacing="0" width="100%">
    <tr>
        <td class="content-left-nav">
			<ul id="<?php echo $this->getId() ?>" class="tabs">
				<li>
					<a href="#" id="<?php echo $this->getId() ?>_options" title="<?php echo Mage::helper('catalog')->__('Options') ?>" class="option-item-link">
						<span><div class="changed" title="<?php echo Mage::helper('catalog')->__('The information in this tab has been changed.') ?>"></div><div class="error" title="<?php echo Mage::helper('catalog')->__('This tab contains invalid data. Please solve the problem before saving.') ?>"></div><div class="option-label-text"><?php echo Mage::helper('catalog')->__('Options') ?></div></span>
					</a>
					<div id="<?php echo $this->getId() ?>_options_content" style="display:none">
						<?php echo $this->getChildHtml('option_form') ?>
					</div>
				</li>
			</ul>
			<ul id="<?php echo $this->getId() ?>_template" class="no-display">
				<li>
					<a href="_url_" id="_id_" title="#{label}" class="option-item-link">
						<span><div class="changed" title="<?php echo Mage::helper('catalog')->__('The information in this tab has been changed.') ?>"></div><div class="error" title="<?php echo Mage::helper('catalog')->__('This tab contains invalid data. Please solve the problem before saving.') ?>"></div><div class="option-label-text">#{label}</div></span>
					</a>
					<div id="_id__content" style="display:none">#{content}</div>
				</li>
			</ul>
        </td>
        <td>
            <div class="content" id="<?php echo $this->getId() ?>_destanation">
            	
            </div>
        </td>
    </tr>
</table>
<script>
var <?php echo $this->getTabJsObjectName() ?> = new Bundle.Tabs('<?php echo $this->getId() ?>','<?php echo $this->getId() ?>_destanation','<?php echo $this->getId() ?>_options','<?php echo $this->getId() ?>_template');
var <?php echo $this->getJsObjectName() ?> = new Bundle.Options('<?php echo $this->getJsContainerHtmlId() ?>',<?php echo $this->getTabJsObjectName() ?>,'<?php echo $this->getUrl('*/*/bundle') ?>', '<?php echo $this->getId() ?>_raw_options', '<?php echo $this->getJsTemplateHtmlId() ?>');
<?php echo $this->getJsObjectName() ?>.jsController = '<?php echo $this->getJsObjectName() ?>';
<?php echo $this->getJsObjectName() ?>.optionLabelNewText = '<?php echo Mage::helper('catalog')->__('Option') ?> ';
<?php foreach ($this->getBundleOptions() as $_option): ?>
<?php echo $this->getJsObjectName() ?>.addItem('<?php echo $_option->getId() ?>','<?php echo $this->getEscaped($_option->getLabel()) ?>','<?php echo $_option->getPosition() ?>',<?php echo $this->getOptionProductsJSON($_option) ?>);
<?php endforeach; ?>
</script>
